//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CraftOptimizer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Storage : global::System.Configuration.ApplicationSettingsBase {
        
        private static Storage defaultInstance = ((Storage)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Storage())));
        
        public static Storage Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Excavating")]
        public string DefaultFarmtype {
            get {
                return ((string)(this["DefaultFarmtype"]));
            }
            set {
                this["DefaultFarmtype"] = value;
            }
        }
    }
}
